### ISSUE TITLE
프로그램 강제 종료

### ISSUE THREAD

**Issue by kjy72** [wr-rainforest/Naver-Webtoon-Downloader#10]
며칠전부터 GUI버전 SHELL 버전 전부 강제 종료 됩니다..
기존 다운받던 웹툰 갱신은 이상이 없는데, 신규로 추가하면 문제가 생기내요..

GUI버전은 그냥 프로그램 강제 종료 돼고..

Shell 버전은
편수 체크 후 URI 캐시를 생성하였습니다라는 메시지 나오고 나서.. 하단에 아래와 같은 메시지가 나오고 나서 강제 종료 됩니다..

처리되지 않은 예외: System.NullReferenceException: 개체 참조가 개체의 인스턴스로 설정되지 않았습니다.

사용버전은 Shell 버전 V2.2.1.1
Gui 버전은 V0.1.107.6 사용중입니다.

윈도우10 업데이트 후에 생기는 문제인지.. 아니면 네이버 웹툰에서 문제가 생기는건지... 도움 부탁드립니다..

**Comment by jay9455** [comment]
저도 같은 문제가 발생하고 있습니다ㅠ

구글링을 해 보니 해당 문제가 C# 자체의 문제인 것 같네요

아마 개발자 분께서 아래처럼 수정 해 주시면 해결 가능할 것 같습니다.
https://ggmouse.tistory.com/72
