### ISSUE TITLE
디렉토리 네임에 작가 이름을 추가 할 수 있을까요?

### ISSUE THREAD

**Issue by kimhomo** [wr-rainforest/Naver-Webtoon-Downloader#2]
덕분에 잘 쓰고 있습니다! 혹시 디렉토리 네임에 자동으로 작가 이름을 추가 할 수 있을까요?

**Comment by wr-rainforest** [comment]
[v2.0.57.2](https://github.com/wr-rainforest/Naver-Webtoon-Downloader/releases/tag/v2.0.57.2) 기능 추가하였습니다.

[폴더명 포맷 설정하기](https://github.com/wr-rainforest/Naver-Webtoon-Downloader#31-configjson)
