### ISSUE TITLE
특정 회차에서 이미지 병합 오류 발생

### ISSUE THREAD

**Issue by wr-rainforest** [wr-rainforest/Naver-Webtoon-Downloader#5]
병합 후 이미지 높이가 65535 픽셀을 초과하는 경우 아래와 같은 오류가 발생합니다.
```csharp
처리되지 않은 예외: System.Runtime.InteropServices.ExternalException: GDI+에서 일반 오류가 발생했습니다.
   위치: System.Drawing.Image.Save(Stream stream, ImageCodecInfo encoder, EncoderParameters encoderParams)
   위치: System.Drawing.Image.Save(MemoryStream stream)
   위치: System.Drawing.ImageConverter.ConvertTo(ITypeDescriptorContext context, CultureInfo culture, Object value, Type destinationType)
   위치: WRforest.NWD.Command.Merge.MergeImages(List`1 imagePathList) 
   위치: WRforest.NWD.Command.Merge.Start(String[] args) 
   위치: WRforest.NWD.Program.Main(String[] args) 
```

**Comment by ImSejin** [comment]
안녕하세요, 어쩌다 우연히 들렀습니다.
다른 merger와 마찬가지로 width나 height 중 하나가 65535px를 초과하면 png로 변환하도록 하면 될 거 같네요.
> JPEG/JFIF supports a maximum image size of 65,535×65,535 pixels. [(출처)](https://en.wikipedia.org/wiki/JPEG)

**Comment by wr-rainforest** [comment]
@ImSejin  png에서도 동일한 오류가 발생합니다.
https://github.com/wr-rainforest/Naver-Webtoon-Downloader/blob/05728b1aac805c293ba9e0c760bf16336ff6a839/Naver-Webtoon-Downloader/NWD/Command/Merge.cs#L90

**Comment by wr-rainforest** [comment]
GDI+ 한계와 관련이 있는것으로 보입니다.
> [Bitmap Constructors](https://docs.microsoft.com/ko-kr/dotnet/api/system.drawing.bitmap.-ctor?)
Due to a limitation of the GDI+ decoder, an System.ArgumentException is thrown if you construct a bitmap from a .png image file with a single dimension greater than 65,535 pixels.

**Comment by ImSejin** [comment]
C#을 알았다면 도움드렸을 텐데, 제가 자바밖에 몰라서.. 아쉽네요

> I'll add this cause of the error as well in hopes it helps some future internet traveler. :)
>
> **GDI+ limits the maximum height of an image to 65500**
> 
> We do some basic image resizing, but in resizing we try to maintain aspect ratio. We have a QA guy who's a little too good at this job; he decided to test this with a ONE pixel wide photo that was 480 pixels tall. When the image was scaled to meet our dimensions, the height was north of 68,000 pixels and our app exploded with `A generic error occurred in GDI+`.
> 
> You can verify this yourself with test:
> ```
>  int width = 480;
>  var height = UInt16.MaxValue - 36; //succeeds at 65499, 65500
>  try
>  {
>    while(true)
>    {
>      var image = new Bitmap(width, height);
>      using(MemoryStream ms = new MemoryStream())
>      {
>        //error will throw from here
>        image.Save(ms, ImageFormat.Jpeg);
>      }
>      height += 1;
>    }
>  }
>  catch(Exception ex)
>  {
>    //explodes at 65501 with "A generic error occurred in GDI+."
>  }
>```
>It's too bad there's not a friendly .net `ArgumentException` thrown in the constructor of `Bitmap`.

[출처](https://qastack.kr/programming/1053052/a-generic-error-occurred-in-gdi-jpeg-image-to-memorystream)

**Comment by sormr** [comment]
안녕하세요 좋은 프로그램 만들어주셔서 감사합니다. 기술적으로 해결이 안된다면 해상도 제한이 넘어가는 편만 절반씩 나눠서 병합하는게 기능적으로는 최선일 것 같은데 어떻게 생각하시는지 궁금합니다.

**Comment by wr-rainforest** [comment]
@sormr 참고하겠습니다.
