### ISSUE TITLE
EpisodeDirectoryNameFormat 패딩이 안되는 버그가 있습니다

### ISSUE THREAD

**Issue by manbokgo** [wr-rainforest/Naver-Webtoon-Downloader#7]
https://github.com/wr-rainforest/Naver-Webtoon-Downloader/blob/44854dbd7c2d8bdecfdec1838da07e734277e447/Naver-Webtoon-Downloader/NWD/FileNameBuilder.cs#L75-L90

83번 라인의 ReplaceFolderName(config.EpisodeDirectoryNameFormat) 로 인해

포맷 스트링 내 :Dn  부분의 :가 전각문자로 처리되어 오류가 납니다

참고해주세요!

**Comment by wr-rainforest** [comment]
#### • 해당 버그가 발생하는 버전 
 - ```v2.0.57.2```
 - ```v2.1.3.1```
 - ```v2.2.1.1```
#### • 오류 메세지 
```csharp
System.FormatException: Input string was not in a correct format.
```

**Comment by wr-rainforest** [comment]
해당 버그의 원인 코드는  [```2cae938```"2020-10-03 20:58:39+0900"](https://github.com/wr-rainforest/Naver-Webtoon-Downloader/commit/2cae938bc38390d70e93448ee56f1449968f5bb2#diff-9ad94d69e8e1dfdab8fdbcf1438f50ede4e757f14f486925961277efc2b2e270) 에서 추가되었습니다. https://github.com/wr-rainforest/Naver-Webtoon-Downloader/blob/b140b0c6ffb34765d222e6e996a1d447c8efaa5f/Naver-Webtoon-Downloader/NWD/FileNameBuilder.cs#L83 https://github.com/wr-rainforest/Naver-Webtoon-Downloader/blob/2cae938bc38390d70e93448ee56f1449968f5bb2/Naver-Webtoon-Downloader/NWD/FileNameBuilder.cs#L83
이후 [```358e761```"2020-11-04 22:03:05+0900"](https://github.com/wr-rainforest/Naver-Webtoon-Downloader/commit/358e7614cb088b31b712de23eb6f0cdd359e92eb#diff-ea52a033fc7935fb88344952381c668fcb22cd1370614d382fdaf9d5122bafe0) 에서 해당 코드를 삭제하였고,

[```9f56357``` "2020-11-05 13:41:56+0900"](https://github.com/wr-rainforest/Naver-Webtoon-Downloader/commit/9f563579314b23e0cec6a3951326c07fb92a63fe) 에서 문자열 조합 이후 ReplaceFolderName을 호출하는 방식으로  새롭게 구현하였습니다.

https://github.com/wr-rainforest/Naver-Webtoon-Downloader/blob/9f563579314b23e0cec6a3951326c07fb92a63fe/Naver-Webtoon-Downloader/Downloader.cs#L196-L221

**Comment by manbokGo** [comment]
개발 버전에서 이미 수정된 부분이었군요 😄 
확인해주셔서 감사합니다! 덕분에 유용하게 잘 쓰고 있어요!

**Comment by wr-rainforest** [comment]
GUI 리포지토리에서 해당 버그를 수정한 버전을 게시하였습니다. 
https://github.com/wr-rainforest/Naver-Webtoon-Downloader-GUI/releases
